### ISSUE TITLE
 Error when checking model input

### ISSUE THREAD

**Issue by cristhianrivera** [alexander-rakhlin/CNN-for-Sentence-Classification-in-Keras#11]
Hello, thank you for your implementation. Sadly I'm just starting to become familiar with Keras and I got the following error after setting up the model for 'CNN-non-static' or 'CNN-static' (so, just working for 'CNN-rand'.

I set the parameters to:

model_variation = 'CNN-non-static'  #  CNN-rand | CNN-non-static | CNN-static
print('Model variation is %s' % model_variation)

**Model Hyperparameters**
sequence_length = 56
embedding_dim = 20          
filter_sizes = (3, 4)
num_filters = 3
dropout_prob = (0.7, 0.8)
hidden_dims = 100

and i got the following error:

ValueError: Error when checking model input: expected dropout_input_3 to have 3 dimensions, but got array with shape (10662L, 56L)

any help would be appreciated

**Comment by alexander-rakhlin** [comment]
Hi. Thanks for the interest. I will check it later. So far please try to temporally change in ~/.keras/keras.json located in your user directory:

`"image_dim_ordering": "tf",`
to
`"image_dim_ordering": "th",`

and let me know whether it helps

**Comment by cristhianrivera** [comment]
Thank you for your answer. 
Same error :

ValueError: Error when checking model input: expected dropout_input_2 to have 3 dimensions, but got array with shape (10662L, 56L).

I'll then try with Tensor Flow backend and tell you my comments.

**Comment by cristhianrivera** [comment]
Hello again, after a lot of problems with TensorFlow, everything is working... although I'd like to know if there's a chance to use Theano instead of TensorFlow.

**Comment by alexander-rakhlin** [comment]
It was originally for Theano. I'll let you know when I have a moment to run it with recent Keras. Version conflict is another possible reason

**Comment by cristhianrivera** [comment]
Thank you for your time. Could you please tell me, which version of Theano and Keras are you using?

**Comment by alexander-rakhlin** [comment]
I have verified it, and it works as intended.  My versions are Theano v0.8, Keras v1.2.0 and it's not too much behind the current 1.2.2. Also, added minor changes, they don't affect overall behavior.
