### ISSUE TITLE
How to use pre-trained word2vec vectors instead of learning them?

### ISSUE THREAD

**Issue by PrudhviRaj12** [alexander-rakhlin/CNN-for-Sentence-Classification-in-Keras#15]
Hi,
Thank you for sharing your code. I am looking at how we can use pre-trained word vectors in this code instead of learning them.

**Comment by alexander-rakhlin** [comment]
Hi,
It is loaded automatically if found in _model_dir_, see [ w2v.py](https://github.com/alexander-rakhlin/CNN-for-Sentence-Classification-in-Keras/blob/master/w2v.py#L24)

**Comment by PrudhviRaj12** [comment]
Oh. Thank you.
