### ISSUE TITLE
vocabulary_inv

### ISSUE THREAD

**Issue by jalyWu** [alexander-rakhlin/CNN-for-Sentence-Classification-in-Keras#18]
Hello, thanks for sharing the implement of the paper. When i read the code of w2v.py, i think the vocabulary_inv is a list while the doc_string says it's a dict. I wonder if something is wrong.

Another question is that when train the word2vec model, it can be seen that sentences constitute of words are used, so why the code first load the data by turning the words into digits and later turn the digits into words for training, Is it necessary?

Thank you!

**Comment by alexander-rakhlin** [comment]
Hi,
Thank you for interest. vocabulary_inv is dictionary. But there is typo in doc string, it is dict {int:str}, not dict {str:int}

The second question - it is not necessary in general, but this is done to reuse keras imdb data set functionality which loads sentences as numeric array.

**Comment by alexander-rakhlin** [comment]
Please see updated version
