### ISSUE TITLE
CNN-static

### ISSUE THREAD

**Issue by akirakitamura19** [alexander-rakhlin/CNN-for-Sentence-Classification-in-Keras#19]
Hi thank you for shaping with your code.

When CNN-static work correctly, how many performance can we expect to get?
I got good performance of CNN-rand and CNN-non-static which are 88-90% after 5 epochs. However, CNN-static got around 65 after even 50 epochs.

In order to work CNN-static right, should I change some parameters?

If giving advice, I really appreciate you.

**Comment by alexander-rakhlin** [comment]
CNN-static has inferior performance. Try to increase embedding dimension.

**Comment by alexander-rakhlin** [comment]
There was a bug with weights embedding. CNN-static does much better, please see updated version.
