### ISSUE TITLE
Is there the same with Graph and Sequential?

### ISSUE THREAD

**Issue by ylqfp** [alexander-rakhlin/CNN-for-Sentence-Classification-in-Keras#2]
Hi, 
you use a graph to organize part-of the model, is it the same with directly use Sequential model?
Why do you use graph?
Thanks!

**Comment by alexander-rakhlin** [comment]
Hi,

Yes, you can avoid Graph model and create several Sequential convolutional models instead (by the number of filters) and merge them. See an example of 2 parallel branches [here](https://karthkk.wordpress.com/2016/03/22/deep-learning-solution-for-netflix-prize/). This shouldn't affect the result.
