### ISSUE TITLE
Problem in code understanding

### ISSUE THREAD

**Issue by Debugger3** [alexander-rakhlin/CNN-for-Sentence-Classification-in-Keras#20]
Hi Rakhlin,
I have doubt in your code written kept in the link "https://github.com/alexander-rakhlin/CNN-for-Sentence-Classification-in-Keras/blob/master/sentiment_cnn.py"  in sentiment_cnn.py file file at line number 81.In this embedding_weights which is a list and embedding_weights[0] is np.narray, how you can pass np.narray as index to the array index. It should technically give error something like "arrays used as indices must be of integer (or boolean) type".

Kindly help me I am stuck at this step. It will help me a lot in my college project. Attaching screenshot for you reference.
![github](https://cloud.githubusercontent.com/assets/13526874/25996634/e65255d0-3735-11e7-92e8-4d3b090149cf.PNG)

**Comment by alexander-rakhlin** [comment]
Hi,

x_train, x_test are integer

**Comment by Debugger3** [comment]
Can you please see initial code. x_train is not integer. It is numpy array. You loaded imdb data in x_train and x_test.

**Comment by alexander-rakhlin** [comment]
They are arrays of integer type and therefore can be used as indices.

**Comment by Debugger3** [comment]
Its a n*m np.array of shape (25000, 400). You can't even give normal array as index too

**Comment by alexander-rakhlin** [comment]
I suggest you to run the code in debugger and see how this indexing works.
