### ISSUE TITLE
instruction on using data_handler with local data

### ISSUE THREAD

**Issue by wailoktam** [alexander-rakhlin/CNN-for-Sentence-Classification-in-Keras#21]
Hi, thanks for sharing your code. Can you tell me how to use the rt-polarity data in the data foler with data_handler? Currently, sentiment_cnn.py would not work if the line loading the imdb data is replaced with loading data supplied by data_handler.  Thanks in advance

**Comment by alexander-rakhlin** [comment]
Hi,

this directory became redundant since I switched to keras data source. But if you browse the repository at pre March 29 [state ](https://github.com/alexander-rakhlin/CNN-for-Sentence-Classification-in-Keras/tree/0a10445fbd0a1c783e6231cd1accb1e1a4e2252f) you will get an idea how to use it
