### ISSUE TITLE
Error in w2v.py line 52

### ISSUE THREAD

**Issue by wangzhe258369** [alexander-rakhlin/CNN-for-Sentence-Classification-in-Keras#24]
Error in w2v.py line 52:
`for key, word in vocabulary_inv.items()}`
I think, it may be `for key, word in enumerate(vocabulary_inv)}`?

**Comment by alexander-rakhlin** [comment]
This line does not return error for me. What is error message in your case?

**Comment by Liwink** [comment]
@alexander-rakhlin 
`vocabulary_inv` is still a `list` instead of a `dict`.

**Comment by alexander-rakhlin** [comment]
Thanks, it will be corrected. However, I do not recommended using local data set due to its small size since Keras data source was introduced, and it is much bigger.

**Comment by alexander-rakhlin** [comment]
Fixed
