### ISSUE TITLE
TypeError: __init__() takes at least 3 arguments (2 given)

### ISSUE THREAD

**Issue by wailoktam** [alexander-rakhlin/CNN-for-Sentence-Classification-in-Keras#25]
Hi, I clone the code and run it. But it seems that Convolution1D needs to be replaced by Conv1D first. And after the replace, I get the following complaints

conv = Conv1D(filters=num_filters, kernel_size=sz, padding="valid", activation="relu",strides=1)(z)
TypeError: __init__() takes at least 3 arguments (2 given)

I try removing (z) but the error message wont change. I also try add a "step" argument (=1)  to input_shape but it does not have any effect either.

Any idea on how to fix this? Many thanks.

**Comment by alexander-rakhlin** [comment]
Hello,
With Keras 2.0.6 and Python 3.6.1 this code runs out of box, provided other necessary packages installed. Hope this helps.
