### ISSUE TITLE
expected input_4 to have shape (None, 185) but got array with shape (1665, 35)

### ISSUE THREAD

**Issue by simarad** [alexander-rakhlin/CNN-for-Sentence-Classification-in-Keras#27]
Hi , I have tried to run the model on my text file on your code. I have changed the parts but In the last line, I got this error:
ValueError: Error when checking input: expected input_4 to have shape (None, 185) but got array with shape (1665, 35)
Do you know how can I solve it? I would really appreciate it.
regards,

**Comment by alexander-rakhlin** [comment]
Hi,
Sorry, I have no time to review your code, but you may ask on https://stackoverflow.com
