### ISSUE TITLE
how to run trained model on sample sentence

### ISSUE THREAD

**Issue by abhigarg** [alexander-rakhlin/CNN-for-Sentence-Classification-in-Keras#28]
I have trained the model by running the sentiment_cnn.py script and saved model weights to a file. Now how can I run it on a custom sentence of say 5 ~ 10 words ?

**Comment by alexander-rakhlin** [comment]
That's possible, however such a short sentences is not what model learned in training, and result may be mediocre. But you can verify it yourself and let us know.
