### ISSUE TITLE
Using Glove or GoogleNews?

### ISSUE THREAD

**Issue by alialwehaibi** [alexander-rakhlin/CNN-for-Sentence-Classification-in-Keras#31]
I see that w2v.py builds a w2v model from text and use it in classification process 'sentiment_cnn'. Is it possible to load a popular trained w2v model such as 'Glove' or 'Google news', instead?

Thanks

**Comment by alexander-rakhlin** [comment]
That's possible, of course. Maybe some code adjustments needed. However, w2v model does not make much difference here.
