### ISSUE TITLE
Wrong model for Y.Kim's TextCNN

### ISSUE THREAD

**Issue by bigdong89** [alexander-rakhlin/CNN-for-Sentence-Classification-in-Keras#32]
You're using wrong model instead of Y.K.'s TextCNN!
TextCNN uses conv2d and maxpooling2d to extract features.
but you use conv1d and maxpooling1d.

Please refer to:
https://github.com/dennybritz/cnn-text-classification-tf/blob/master/text_cnn.py

For original pager:
https://arxiv.org/pdf/1408.5882.pdf

**Comment by alexander-rakhlin** [comment]
Thanks, I am using correct model, and reference to original paper is in the README of the repo.
