### ISSUE TITLE
Using pre-trained google word embeddings

### ISSUE THREAD

**Issue by haskarb** [alexander-rakhlin/CNN-for-Sentence-Classification-in-Keras#33]
Hi @alexander-rakhlin ,

Thanks for sharing your code. 
I have a small query; how can I use google pre-trained binary file.

Thanks :)

**Comment by alexander-rakhlin** [comment]
You can use it in place of word2vec model in the code, but you need to adjust details like embedding dimensionality and interface - I don't remember whether it different or not.

**Comment by haskarb** [comment]
I tried to set embedding size to 300, but it not working :(

**Comment by alexander-rakhlin** [comment]
So you need to figure out how to incorporate it yourself, because I do not know too.
