### ISSUE TITLE
Only words, no sentences

### ISSUE THREAD

**Issue by vasilikivmo** [alexander-rakhlin/CNN-for-Sentence-Classification-in-Keras#35]
What modification should I made if I want to train the model with my own dataset, without separating it per sentences? I only have a document of words and a label for each word. Hence, I would like to have a shape of the dataset [rows, colums] where rows is the number of words in my dataset) and columns is a number of 300 or 400 vector representation of each word. As a result each label will be assigned to each word separately, and not to the whole sentence.
I have modified the inner functions in order for the words to be understood, but in the final result, I cannot set correctly the vectors dimensionality of each word.

I am aware that this is a very specific question, obviously different than what this implementation provides, but since it is very clear what it does, I would like to apply it on my own results, if it is possible.

Thank you in advance!

**Comment by boshuru** [comment]
Please provide an example of your data? If you basically just have a document containing rows, each row for one word and a word vector, what you have is a word embedding table. What's the point of using codes in this git? Alexandra's codes implemented Kim's CNN model in 2014 paper on CNN text classification. Which is defaco for sentence or documents.
