### ISSUE TITLE
问题咨询

### ISSUE THREAD

**Issue by GongQin721** [alexander-rakhlin/CNN-for-Sentence-Classification-in-Keras#36]
请问下你用的keras是什么版本呢

**Comment by boshuru** [comment]
I tried Alexander-Rakhlin's code in my Keras 2.0.8, Python 3.6 environment and everything is fine.

**Comment by GongQin721** [comment]
ok ,thank you !




------------------ 原始邮件 ------------------
发件人: "boshuru"<notifications@github.com>;
发送时间: 2018年5月7日(星期一) 晚上11:24
收件人: "alexander-rakhlin/CNN-for-Sentence-Classification-in-Keras"<CNN-for-Sentence-Classification-in-Keras@noreply.github.com>;
抄送: "紫薰苜蓿"<1772362617@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [alexander-rakhlin/CNN-for-Sentence-Classification-in-Keras] 问题咨询 (#36)




I tried Alexander-Rakhlin's code in my Keras 2.0.8, Python 3.6 environment and everything is fine.

**Comment by GongQin721** [comment]
用不同版本的kears会对结果有影响吗？




------------------ 原始邮件 ------------------
发件人: "boshuru"<notifications@github.com>;
发送时间: 2018年5月7日(星期一) 晚上11:24
收件人: "alexander-rakhlin/CNN-for-Sentence-Classification-in-Keras"<CNN-for-Sentence-Classification-in-Keras@noreply.github.com>;
抄送: "紫薰苜蓿"<1772362617@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [alexander-rakhlin/CNN-for-Sentence-Classification-in-Keras] 问题咨询 (#36)




I tried Alexander-Rakhlin's code in my Keras 2.0.8, Python 3.6 environment and everything is fine.

**Comment by boshuru** [comment]
I am not sure on this specific code, but I have experienced issues when trying to use pretrained keras models on another machine running a different version. To keep your working environment organized, use virtual environments for different projects.

**Comment by GongQin721** [comment]
你的意思是在linux系统下去做仿真吗




------------------ 原始邮件 ------------------
发件人: "boshuru"<notifications@github.com>;
发送时间: 2018年5月8日(星期二) 中午11:09
收件人: "alexander-rakhlin/CNN-for-Sentence-Classification-in-Keras"<CNN-for-Sentence-Classification-in-Keras@noreply.github.com>;
抄送: "紫薰苜蓿"<1772362617@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [alexander-rakhlin/CNN-for-Sentence-Classification-in-Keras] 问题咨询 (#36)




I am not sure on this specific code, but I have experienced issues when trying to use pretrained keras models on another machine running a different version. To keep your working environment organized, use virtual environments for different projects.

**Comment by boshuru** [comment]
Create an virtual Python environment with Anaconda, which runs good on Linux, Mac, Windows... In that environment, install keras, tensorflow and etc. You can find a lot of online tutorial on this.

**Comment by GongQin721** [comment]
哦，你说的这个哦，我就用的anaconda，里面包含了很多模块，然后用spyder去编译




------------------ 原始邮件 ------------------
发件人: "boshuru"<notifications@github.com>;
发送时间: 2018年5月8日(星期二) 中午11:23
收件人: "alexander-rakhlin/CNN-for-Sentence-Classification-in-Keras"<CNN-for-Sentence-Classification-in-Keras@noreply.github.com>;
抄送: "紫薰苜蓿"<1772362617@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [alexander-rakhlin/CNN-for-Sentence-Classification-in-Keras] 问题咨询 (#36)




Create an virtual Python environment with Anaconda, which runs good on Linux, Mac, Windows... In that environment, install keras, tensorflow and etc. You can find a lot of online tutorial on this.

**Comment by boshuru** [comment]
guys please use English. I cannot assume Alex, the owner of this git project, understand and type in Chinese....
