### ISSUE TITLE
accuracy

### ISSUE THREAD

**Issue by zxs1995** [alexander-rakhlin/CNN-for-Sentence-Classification-in-Keras#38]
请问您的这个实现可以达到test集在88%左右吗

**Comment by boshuru** [comment]
English please.

**Comment by zxs1995** [comment]
Might I ask you if your implementation could achieve at 88% of accuracy on a test set?

**Comment by alexander-rakhlin** [comment]
In the "CNN-rand" and "CNN-non-static" settings it was getting to 88-90% This depends on random initialization though.
