### ISSUE TITLE
The model always predicts the same label

### ISSUE THREAD

**Issue by flaviomerenda** [alexander-rakhlin/CNN-for-Sentence-Classification-in-Keras#39]
Update: 

I think that I solved the problem changing "argmax" with a threshold:

y_proba = model.predict(x_test)
Y_classes = (y_proba > 0.5).astype(np.int)
print(Y_classes)

Is it right?

------------------------------------------------------------------------------------------------------------------------------------------

Hi,

I run your code with another dataset in order to train this model for a binary classification task; It works fine, but when I print the predictions, it always assigns the same label (0 - absent) to whole instances.

This is the code used:

y_proba = model.predict(x_test)
Y_classes = y_proba.argmax(axis=-1)

Can you understand why? I'm quite new to deep learning and CNN

**Comment by alexander-rakhlin** [comment]
Hi,
`Y_classes = (y_proba > 0.5).astype(np.int)` should be correct.
