### ISSUE TITLE
Two fully-connected layers after convolutions

### ISSUE THREAD

**Issue by jantrienes** [alexander-rakhlin/CNN-for-Sentence-Classification-in-Keras#40]
Thanks for sharing this nice implementation of the Yoon Kim CNN!

I noticed that you've added two fully connected layers after the dropout of the convolutions. Just to confirm, is this another deviation from the original paper? How I see it, the original paper only uses one fully connected layer.

https://github.com/alexander-rakhlin/CNN-for-Sentence-Classification-in-Keras/blob/0c7a61f428470d014177ad4a98fef7ad4b86d387/sentiment_cnn.py#L151-L153

**Comment by alexander-rakhlin** [comment]
Hi,
The paper does not specify this exactly, but you probably correct: one vs. two fully connected layers.
